### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by bat-nik** [Soopcha/CGshechkaTASK4#47]
---
### 1

https://github.com/Soopcha/CGshechkaTASK4/blob/d7d14593c6897a7f28d0eee1004668ab9e2a3568/src/main/java/com/cgvsu/math/matrix/Matrix4x4.java#L131

По названию метода не очевидно, что он делает перспективное деление. Можно переименовать метод или разбить его на два разных метода (умножение и перспективное деление).

---
### 2

https://github.com/Soopcha/CGshechkaTASK4/blob/d7d14593c6897a7f28d0eee1004668ab9e2a3568/src/main/java/com/cgvsu/math/vector/Vector3.java#L209

Сообщение об ошибке можно сделать более информативным, например:

```java
throw new IllegalArgumentException("Vector3 не имеет координаты с индексом " + index);
```

--- 
### 3

https://github.com/Soopcha/CGshechkaTASK4/blob/d7d14593c6897a7f28d0eee1004668ab9e2a3568/src/main/java/com/cgvsu/math/vector/Vector3.java#L81

Здесь и в остальных местах лучше не сравнивать вещественные типы оператором `==`, а использовать сравнение с допустимой погрешностью, например:

```java
if (Math.abs(scalar) < EPS) {
```

---
### 4

https://github.com/Soopcha/CGshechkaTASK4/blob/d7d14593c6897a7f28d0eee1004668ab9e2a3568/src/main/java/com/cgvsu/model/Model.java#L11

Лучше сделать поля приватными и использовать геттеры и сеттеры. Это касается и других классов.

---
### 5

https://github.com/Soopcha/CGshechkaTASK4/blob/d7d14593c6897a7f28d0eee1004668ab9e2a3568/src/main/java/com/cgvsu/triangulation/Normals.java#L48

В реализации метода можно использовать уже готовый метод нормализации из класса вектора вместо деления каждой координаты на длину вручную.

Кроме того, можно вынести класс из пакета триангуляции куда-то в более подходящее место.

**Comment by valieree** [comment]
выполнено все (приватные поля в модели сделать не вышло)
